# Generated by Django 5.2 on 2025-04-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeseries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('entry_id', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('light_index', models.FloatField()),
                ('atmosphere', models.FloatField()),
                ('voltage', models.FloatField()),
                ('was_interpolated', models.BooleanField()),
            ],
        ),
    ]
